const navType = {
  TOGGLE_SLIDE_MENU: 'TOGGLE_SLIDE_MENU',
  TOGGLE_MAIN_OVERLAY: 'TOGGLE_MAIN_OVERLAY',
  SET_CURRENT_LOCATION: 'SET_CURRENT_LOCATION',
  SET_MEDIA_TYPE: 'SET_MEDIA_TYPE',
  SET_CHANNEL: 'SET_CHANNEL',
};

export default navType;
